### PR TITLE
fix No interface method startReplaceableGroup !!

### PR DESCRIPTION
**Pull request by CMingTseng**
1. ues com.google.accompanist:accompanist-coil replace dev.chrisbanes.accompanist:accompanist-coil

2. navigation-compose upgrade to 2.4.0-alpha02 !! (still error need fix)

requestBuilder can ref : https://github.com/google/accompanist/blob/350f4b99fe9c04a074c9e39e25cf0eb7786ef2d7/sample/src/main/java/com/google/accompanist/sample/coil/CoilBasicSample.kt#L87

Ref :  https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.0.0-beta07

      Note: Libraries dependent on Compose will need to recompile with version 1.0.0‑beta07. Otherwise, libraries may encounter a NoSuchMethodError, such as:
      java.lang.NoSuchMethodError: No interface method startReplaceableGroup(ILjava/lang/String;)V in class Landroidx/compose/runtime/Composer; or its super classes. (Ia34e6)

### CODE REVIEW

**Comment by ellisonchan** [comment]
CMingTseng, Hi.

针对startReplaceableGroup函数缺失导致运行失败的fix，上次已经有朋友修改了，和你本次push的修正冲突了。
https://github.com/ellisonchan/ComposeMovie/pull/3

> 2. navigation-compose upgrade to 2.4.0-alpha02 !! (still error need fix)

另外，navigation的修正，指的是改完了仍然有问题吗？

**Review by ellisonchan — APPROVED** [review]

**Comment by CMingTseng** [comment]
> navigation的修正，指的是改完了仍然有问题吗？

我是臨時改完

1.X.X版的NAV有一個 library 的TAG可用

但是 2.4.X的移除了 

類似這樣的一些小地方

需要大神介入一下

但是 切換是可以的
